# Generated by Django 3.2.7 on 2023-01-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0002_auto_20230103_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='User',
            new_name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
