# Generated by Django 3.2.7 on 2023-01-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0003_auto_20230103_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
